title: Oddpennine
description: A bold typographic theme inspired by Swiss design.
social_link: 'https://bsky.app/profile/lionmelody.bsky.social'
social_username: 'https://bsky.app/profile/lionmelody.bsky.social'
github_repo: athena
github_username: oddpennine
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /everyrights
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
